
name: Commit Message Lint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    uses: GradientHQ/.github/.github/workflows/commitlint.yml@main
